version: "3.8"
services:
  nginx:
    image: nginx-ingress:0.1
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ingress
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]

# docker network create --driver overlay ingress-routing
networks:
  ingress:
    external: true
    name: ingress-routing
