version: "3.8"
services:

  nginx:
    image: nginx:alpine
    networks:
      - ingress
    configs:
      - source: nginx_config 
        target: /etc/nginx/conf.d/virtual-host.conf
      - source: nginx_options 
        target: /etc/nginx/options-ssl-nginx.conf
      - source: nginx_dhparams
        target: /etc/nginx/ssl-dhparams.pem
    secrets:
      - nginx_key
      - nginx_cert
    deploy:
      replicas: 5 
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        ingress.host: my-service.company.tld
        ingress.port: 443
        ingress.virtual_proto: https 
        ingress.ssl: enable
        ingress.ssl_redirect: enable
        
# Self-signed cert
# mkdir certs && sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout ./certs/nginx.key -out ./certs/nginx.crt
# cd certs
# docker secret create nginx_cert nginx.crt
# docker secret create nginx_key nginx.key

secrets:
  nginx_key:
    external: true
  nginx_cert:
    external: true

configs:
  nginx_config:
    file: ./nginx-ssl/nginx-no-proxy.conf
  nginx_options:
    file: ./nginx-ssl/options-ssl-nginx.conf
  nginx_dhparams:
    file: ./nginx-ssl/ssl-dhparams.pem

networks:
  ingress:
    external: true
    name: ingress-routing